global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node
    scrape_interval: 15s
    static_configs:
      - targets: ["exporter:9100"]
  - job_name: flow
    scrape_interval: 5s
    static_configs:
      - targets:
          - "consensus_1:8080"
          - "consensus_2:8080"
          - "consensus_3:8080"
          - "consensus_4:8080"
          - "consensus_5:8080"
          - "consensus_6:8080"
          - "consensus_7:8080"
          - "consensus_8:8080"
          - "consensus_9:8080"
          - "consensus_10:8080"
