name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run Revive Action
      uses: morphy2k/revive-action@v1.3.0
      with:
        config: revive.toml
        exclude: "cli/flow/cadence/vscode/cadence_bin.go"
        path: "./..."
      env:
        # GitHub token for annotations
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check formatting
      run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)
